[c]
symbol = " "

[cpp]
disabled = false
symbol = " "

[character]

[cmd_duration]

[conda]

[directory]

[docker_context]

[dotnet]

[fill]

[git_branch]

[git_commit]

[git_state]

[git_metrics]

[git_status]

[gradle]

[java]

[kotlin]

[nodejs]

[ocaml]

[os]

[os.symbols]

[package]

[python]

[rust]

[scala]
detect_folders = [] 

[shell]

[status]

[swift]

[typst]

[username]


